[package]
name = "rat-server"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true, features = ["cargo", "derive", "error-context", "help", "usage"] }
futures-util = { workspace = true }
log = { workspace = true }
poem = { workspace = true, features = ["rustls", "static-files"] }
poem-openapi = { workspace = true, features = ["swagger-ui"] }
postcard = { workspace = true, features = ["use-std"] }
rat-common = { path = "../rat-common" }
rustls = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "signal"] }
tokio-rustls = { workspace = true }
tokio-stream = { workspace = true }

[lints]
workspace = true
