# Reference: https://docs.docker.com/reference/compose-file/
name: remote-access-trojan

services:
  ubuntu-client:
    build:
      context: .
      target: ubuntu-client-runtime
    command: [ "--host", "server:12110", "--log-path", "/client.log" ]
    image: rat-ubuntu-client

  centos-client:
    build:
      context: .
      target: centos-client-runtime
    command: [ "--host", "server:12110", "--log-path", "/client.log" ]
    image: rat-centos-client

  debian-client:
    build:
      context: .
      target: debian-client-runtime
    command: [ "--host", "server:12110", "--log-path", "/client.log" ]
    image: rat-debian-client

  alpine-client:
    build:
      context: .
      target: alpine-client-runtime
    command: [ "--host", "server:12110", "--log-path", "/client.log" ]
    image: rat-alpine-client

  server:
    build:
      context: .
      target: server-runtime
    command: [ "--log-path", "/client.log", "--admin-host", "0.0.0.0:12111" ]
    hostname: server
    image: rat-server
    ports:
      - "12110:12110"
      - "12111:12111"
