# Reference: https://docs.docker.com/reference/compose-file/
name: remote-access-trojan

services:
  client:
    build:
      context: .
      target: client-runtime
    command: [ "--host", "server:12110", "--log-path", "/client.log" ]
    deploy:
      replicas: 3
    image: rat-client

  server:
    build:
      context: .
      target: server-runtime
    command: [ "--log-path", "/client.log" ]
    hostname: server
    image: rat-server
    ports:
      - "12110:12110"
      - "12111:12111"
