[package]
name = "rat-client"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true, features = ["cargo", "derive", "error-context", "help", "usage"] }
libc = { workspace = true }
log = { workspace = true }
postcard = { workspace = true, features = ["use-std"] }
rat-common = { path = "../rat-common" }
rustls = { workspace = true }
sysinfo = { workspace = true, features = ["system"] }
tokio = { workspace = true, features = ["io-util", "net", "process", "rt-multi-thread", "signal", "time"] }
tokio-rustls = { workspace = true }
windows-service = { workspace = true }

[dependencies.windows-sys]
workspace = true

[lints]
workspace = true
