[package]
name = "rat-common"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
log = { workspace = true }
poem-openapi = { workspace = true }
serde = { workspace = true, features = ["derive", "rc", "std"] }
simplelog = { workspace = true, features = ["local-offset", "termcolor"] }
slotmap = { workspace = true }
tokio = { workspace = true }

[lints]
workspace = true
