[package]
name = "rat-common"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
log = { workspace = true }
serde = { workspace = true, features = ["derive", "std"] }
simplelog = { workspace = true, features = ["local-offset", "termcolor"] }
tokio = { workspace = true, features = ["io-util", "macros", "net", "rt", "sync"] }

[lints]
workspace = true
