[package]
name = "rat-common"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true, optional = true }
async-trait = { workspace = true, optional = true }
const_format = { workspace = true }
log = { workspace = true, optional = true }
poem-openapi = { workspace = true, optional = true }
serde = { workspace = true, features = ["alloc", "derive", "rc"] }
serde_json = { workspace = true, optional = true }
simplelog = { workspace = true, optional = true, features = ["local-offset", "termcolor"] }
slotmap = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }
widestring = { workspace = true, features = ["alloc"] }

[dependencies.windows-sys]
workspace = true
features = [
    "Win32",
        "Win32_System",
            "Win32_System_Ioctl",
            "Win32_System_Threading",
]

[lints]
workspace = true

[features]
default = ["std"]
std = ["dep:anyhow", "dep:async-trait", "dep:log", "dep:poem-openapi", "dep:serde_json", "dep:simplelog", "dep:slotmap", "dep:tokio"]
