/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all clients connected to the C&C server. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["AdminResult_list_ClientAPI"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients/{addr}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get information about a specific client by its address. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    addr: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["AdminResult_ClientAPI"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients/{addr}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all sessions of a specific client */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    addr: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["AdminResult_list_SessionMetadata"];
                    };
                };
            };
        };
        put?: never;
        /** Create a new session for a specific client */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    addr: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["SessionCreateRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["AdminResult_SessionMetadata"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients/{addr}/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an existing session of a specific client */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    addr: string;
                    session_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["AdminResult_SnowflakeId"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients/{addr}/sessions/{session_id}/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listen for output from an existing session of a specific client */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    addr: string;
                    session_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": components["schemas"]["AdminResult_SessionOutput"][];
                    };
                };
            };
        };
        put?: never;
        /** Send input to an existing session of a specific client */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    addr: string;
                    session_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["SessionInput"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["AdminResult_SnowflakeId"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        AdminResultCode: "success" | "dead-server" | "invalid-input" | "client-not-found" | "other";
        /** AdminResult_ClientAPI */
        AdminResult_ClientAPI: {
            code: components["schemas"]["AdminResultCode"];
            error?: string;
            data?: components["schemas"]["ClientAPI"];
        };
        /** AdminResult_SessionMetadata */
        AdminResult_SessionMetadata: {
            code: components["schemas"]["AdminResultCode"];
            error?: string;
            data?: components["schemas"]["SessionMetadata"];
        };
        /** AdminResult_SessionOutput */
        AdminResult_SessionOutput: {
            code: components["schemas"]["AdminResultCode"];
            error?: string;
            data?: components["schemas"]["SessionOutput"];
        };
        /** AdminResult_SnowflakeId */
        AdminResult_SnowflakeId: {
            code: components["schemas"]["AdminResultCode"];
            error?: string;
            /** Format: snowflake */
            data?: string;
        };
        /** AdminResult_list_ClientAPI */
        AdminResult_list_ClientAPI: {
            code: components["schemas"]["AdminResultCode"];
            error?: string;
            data?: components["schemas"]["ClientAPI"][];
        };
        /** AdminResult_list_SessionMetadata */
        AdminResult_list_SessionMetadata: {
            code: components["schemas"]["AdminResultCode"];
            error?: string;
            data?: components["schemas"]["SessionMetadata"][];
        };
        /** ClientAPI */
        ClientAPI: {
            address: string;
            info?: components["schemas"]["SystemInfo"];
        };
        /** @enum {string} */
        SessionCreateRequest: "terminal";
        SessionInput: components["schemas"]["SessionInputTerminalStdin"] | components["schemas"]["SessionInputClose"];
        /** SessionInputClose */
        SessionInputClose: Record<string, never>;
        /** SessionInputTerminalStdin */
        SessionInputTerminalStdin: {
            data: string;
        };
        /** SessionMetadata */
        SessionMetadata: {
            /** Format: snowflake */
            id: string;
            inner: components["schemas"]["SessionMetadataInner"];
        };
        SessionMetadataInner: components["schemas"]["SessionMetadataInner_SessionMetadataInnerTerminal"];
        /** SessionMetadataInnerTerminal */
        SessionMetadataInnerTerminal: {
            /** Format: uint32 */
            pid: number;
        };
        SessionMetadataInner_SessionMetadataInnerTerminal: {
            /**
             * @example terminal
             * @enum {string}
             */
            type: "terminal";
        } & components["schemas"]["SessionMetadataInnerTerminal"];
        SessionOutput: components["schemas"]["SessionOutputTerminalStdout"] | components["schemas"]["SessionOutputTerminalStderr"] | components["schemas"]["SessionOutputTerminalClosed"];
        /** SessionOutputTerminalClosed */
        SessionOutputTerminalClosed: Record<string, never>;
        /** SessionOutputTerminalStderr */
        SessionOutputTerminalStderr: {
            data: string;
        };
        /** SessionOutputTerminalStdout */
        SessionOutputTerminalStdout: {
            data: string;
        };
        /** SystemInfo */
        SystemInfo: {
            /** Format: uint64 */
            boot_time: number;
            cpu_arch: string;
            distribution_id: string;
            host_name?: string;
            kernel_long_version: string;
            kernel_version?: string;
            long_os_version?: string;
            name?: string;
            /** Format: uint64 */
            open_files_limit?: number;
            os_version?: string;
            /** Format: uint64 */
            physical_core_count?: number;
            /** Format: uint64 */
            uptime: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
