# Reference: https://docs.docker.com/reference/compose-file/
name: remote-access-trojan

services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    container_name: devcontainer
    environment:
      CARGO_TARGET_DIR: /target
      RUST_BACKTRACE: "1"
    ports:
      - "5173:5173" # development Vite server
      - "12110:12110" # C&C server
      - "12111:8000" # OpenAPI server (socat-forwarded)
    volumes:
      - ..:/workspaces/remote-access-trojan
    working_dir: /workspaces/remote-access-trojan
