use windows_sys::Win32::System::Threading::{
    PROCESS_CREATE_THREAD, PROCESS_TERMINATE, PROCESS_VM_OPERATION, PROCESS_VM_WRITE,
};

pub mod kernel;
pub mod utils;

pub const RAT_CLIENT_SERVICE_NAME: &str = "Violet";
pub const PROCESS_PROTECTED_ACCESS: u32 = PROCESS_CREATE_THREAD
    // | PROCESS_DUP_HANDLE
    // | PROCESS_SUSPEND_RESUME
    | PROCESS_TERMINATE
    | PROCESS_VM_OPERATION
    | PROCESS_VM_WRITE;
