name: Build

on: [ push, pull_request ]

permissions:
  contents: read

jobs:
  windows:
    name: Build Windows executable
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.94
          cache: false
          rustflags: ""

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Setup tools
        shell: cmd
        run: |
          extern\wdksetup.exe /features + /log "%cd%\wdksetup.log" /quiet
          cargo install cargo-wdk

      - name: Build Windows kernel driver
        working-directory: rat-driver
        run: cargo wdk build --profile release || true  # Ignore this because our .inx fucks up infverif

      - name: Build UEFI image
        working-directory: rat-efi
        run: cargo build --release

      - name: Build Windows executables
        run: cargo build --release

      - name: Upload Windows executables
        uses: actions/upload-artifact@v7
        with:
          name: windows
          path: |
            target/release/rat-client.exe
            target/release/rat-dropper.exe
            target/release/rat-server.exe

  docker:
    name: Build Docker images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build Docker images
        run: docker compose build

      - name: Extract Linux executables
        run: |
          mkdir -p build

          docker create --name temp rat-alpine-client
          docker cp temp:/rat-client build/rat-client
          docker rm temp
          ldd build/rat-client

          docker create --name temp rat-server
          docker cp temp:/rat-server build/rat-server
          docker rm temp
          ldd build/rat-server

      - name: Save Docker images
        run: |
          mkdir -p build
          docker image ls
          docker save -o build/alpine-client.tar rat-alpine-client
          docker save -o build/centos-client.tar rat-centos-client
          docker save -o build/debian-client.tar rat-debian-client
          docker save -o build/ubuntu-client.tar rat-ubuntu-client
          docker save -o build/server.tar rat-server

      - name: Upload Linux executable
        uses: actions/upload-artifact@v7
        with:
          name: linux
          path: |
            build/rat-client
            build/rat-server

      - name: Upload Docker images
        uses: actions/upload-artifact@v7
        with:
          name: docker-images
          path: build/*.tar
