name: Lint

on: [ push, pull_request ]

permissions:
  contents: read

jobs:
  rustfmt:
    name: Run rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly,1.94
          components: clippy,rustfmt
          cache: false
          rustflags: ""
          target: x86_64-unknown-uefi

      - name: Run rustfmt via cargo fmt
        run: cargo +nightly fmt -- --check

      - name: Run rustfmt via cargo fmt (kernel driver)
        working-directory: rat-driver
        run: cargo +nightly fmt -- --check

      - name: Run rustfmt via cargo fmt (UEFI)
        working-directory: rat-efi
        run: cargo +nightly fmt -- --check

  clippy:
    name: Run clippy
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly,1.94
          components: clippy,rustfmt
          cache: false
          rustflags: ""
          target: x86_64-unknown-uefi

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Setup tools
        shell: cmd
        run: |
          extern\wdksetup.exe /features + /log "%cd%\wdksetup.log" /quiet
          cargo install cargo-wdk

      - name: Run clippy
        run: cargo clippy --all-features --no-deps -- -D warnings

      - name: Run clippy (kernel driver)
        working-directory: rat-driver
        run: |
          cargo wdk build || true
          cargo clippy --all-features --no-deps -- -D warnings

      - name: Run clippy (UEFI)
        working-directory: rat-efi
        run: cargo clippy --all-features --no-deps -- -D warnings
