[package]
name = "rat-dropper"
version.workspace = true
edition.workspace = true

[dependencies]
rat-common = { path = "../rat-common" }
zstd = { workspace = true }

[dependencies.windows-sys]
workspace = true
features = [
    "Win32",
        "Win32_Security",
        "Win32_System",
            "Win32_System_Ioctl",
            "Win32_System_LibraryLoader",
            "Win32_System_Threading",
]

[build-dependencies]
crc32fast = { workspace = true }
sha2 = { workspace = true }
zstd = { workspace = true }

[lints]
workspace = true
